-- CreateTable
CREATE TABLE "Food" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Category" TEXT,
    "Description" TEXT,
    "Nutrient_Data_Bank_Number" INTEGER NOT NULL,
    "Alpha_Carotene" REAL,
    "Beta_Carotene" REAL,
    "Beta_Cryptoxanthin" REAL,
    "Carbohydrate" REAL,
    "Cholesterol" REAL,
    "Choline" REAL,
    "Fiber" REAL,
    "Lutein_and_Zeaxanthin" REAL,
    "Lycopene" REAL,
    "Niacin" REAL,
    "Protein" REAL,
    "Retinol" REAL,
    "Riboflavin" REAL,
    "Selenium" REAL,
    "Sugar_Total" REAL,
    "Thiamin" REAL,
    "Water" REAL,
    "Fat_Monosaturated_Fat" REAL,
    "Fat_Polysaturated_Fat" REAL,
    "Fat_Saturated_Fat" REAL,
    "Fat_Total_Lipid" REAL,
    "Major_Minerals_Calcium" REAL,
    "Major_Minerals_Copper" REAL,
    "Major_Minerals_Iron" REAL,
    "Major_Minerals_Magnesium" REAL,
    "Major_Minerals_Phosphorus" REAL,
    "Major_Minerals_Potassium" REAL,
    "Major_Minerals_Sodium" REAL,
    "Major_Minerals_Zinc" REAL,
    "Vitamins_Vitamin_A_RAE" REAL,
    "Vitamins_Vitamin_B12" REAL,
    "Vitamins_Vitamin_B6" REAL,
    "Vitamins_Vitamin_C" REAL,
    "Vitamins_Vitamin_E" REAL,
    "Vitamins_Vitamin_K" REAL
);
